"""
Priors Loader Module

This module provides utilities to load and process prior information
(likelihood maps and topology masks) generated by Project A (Image Segmentation).

Key functionalities:
- Load likelihood.npy and topology_mask.npy for a given image
- Handle size alignment using metadata.json
- Resize priors to match original image dimensions
- Provide efficient caching mechanism
"""

import json
import numpy as np
from pathlib import Path
from typing import Dict, Tuple, Optional
import cv2


class PriorsLoader:
    """
    Loader for segmentation priors (likelihood and topology masks).

    Attributes:
        priors_root (Path): Root directory containing priors data
        cache (Dict): In-memory cache for loaded priors
        use_cache (bool): Whether to use caching
    """

    def __init__(self, priors_root: str, use_cache: bool = True):
        """
        Initialize the priors loader.

        Args:
            priors_root: Root directory containing priors (e.g., outputs/priors)
            use_cache: Whether to cache loaded priors in memory
        """
        self.priors_root = Path(priors_root)
        self.use_cache = use_cache
        self.cache: Dict[str, Dict] = {}

        if not self.priors_root.exists():
            raise FileNotFoundError(f"Priors root directory not found: {self.priors_root}")

    def get_image_key(self, image_path: str, split: str = "val") -> str:
        """
        Convert image path to image key used in priors directory structure.

        Example:
            images/val/cam0_1_557_pear_2.jpg -> cam0_1_557_pear_2

        Args:
            image_path: Path to the image file
            split: Dataset split (train/val/test)

        Returns:
            Image key (filename without extension)
        """
        image_path = Path(image_path)
        return image_path.stem

    def load_priors(
        self,
        image_path: str,
        split: str = "val",
        resize_to_original: bool = True
    ) -> Dict[str, np.ndarray]:
        """
        Load likelihood and topology mask for a given image.

        Args:
            image_path: Path to the image file
            split: Dataset split (train/val/test)
            resize_to_original: Whether to resize priors to original image size

        Returns:
            Dictionary containing:
                - 'likelihood': [H, W] float32 array
                - 'topology_mask': [H, W] uint8 array
                - 'metadata': metadata dict
        """
        image_key = self.get_image_key(image_path, split)
        cache_key = f"{split}/{image_key}"

        # Check cache
        if self.use_cache and cache_key in self.cache:
            return self.cache[cache_key]

        # Construct paths
        priors_dir = self.priors_root / split / image_key
        likelihood_path = priors_dir / "likelihood.npy"
        topology_mask_path = priors_dir / "topology_mask.npy"
        metadata_path = priors_dir / "metadata.json"

        # Check existence
        if not priors_dir.exists():
            raise FileNotFoundError(f"Priors directory not found: {priors_dir}")

        # Load files
        likelihood = np.load(str(likelihood_path))
        topology_mask = np.load(str(topology_mask_path))

        with open(metadata_path, 'r') as f:
            metadata = json.load(f)

        # Resize if needed
        if resize_to_original and metadata.get('resized', False):
            original_shape = tuple(metadata['original_shape_hw'])
            likelihood = self._resize_array(likelihood, original_shape, interpolation='linear')
            topology_mask = self._resize_array(topology_mask, original_shape, interpolation='nearest')

        result = {
            'likelihood': likelihood,
            'topology_mask': topology_mask,
            'metadata': metadata
        }

        # Cache result
        if self.use_cache:
            self.cache[cache_key] = result

        return result

    def _resize_array(
        self,
        array: np.ndarray,
        target_shape: Tuple[int, int],
        interpolation: str = 'linear'
    ) -> np.ndarray:
        """
        Resize a 2D array to target shape.

        Args:
            array: Input array [H, W]
            target_shape: Target shape (H, W)
            interpolation: 'linear' or 'nearest'

        Returns:
            Resized array
        """
        interp_map = {
            'linear': cv2.INTER_LINEAR,
            'nearest': cv2.INTER_NEAREST
        }

        if array.shape == target_shape:
            return array

        # OpenCV uses (W, H) format
        target_size = (target_shape[1], target_shape[0])
        resized = cv2.resize(array, target_size, interpolation=interp_map[interpolation])

        return resized

    def load_batch(
        self,
        image_paths: list,
        split: str = "val",
        resize_to_original: bool = True
    ) -> list:
        """
        Load priors for a batch of images.

        Args:
            image_paths: List of image paths
            split: Dataset split
            resize_to_original: Whether to resize priors

        Returns:
            List of priors dictionaries
        """
        return [
            self.load_priors(img_path, split, resize_to_original)
            for img_path in image_paths
        ]

    def clear_cache(self):
        """Clear the in-memory cache."""
        self.cache.clear()

    def get_cache_size(self) -> int:
        """Get the number of cached items."""
        return len(self.cache)


def load_priors_manifest(priors_root: str, split: str = "val") -> Dict:
    """
    Load the manifest file for a given split.

    The manifest contains metadata about all images in the split.

    Args:
        priors_root: Root directory containing priors
        split: Dataset split (train/val/test)

    Returns:
        Manifest dictionary
    """
    manifest_path = Path(priors_root) / "manifests" / f"{split}.json"

    if not manifest_path.exists():
        raise FileNotFoundError(f"Manifest not found: {manifest_path}")

    with open(manifest_path, 'r') as f:
        manifest = json.load(f)

    return manifest


if __name__ == "__main__":
    # Example usage
    loader = PriorsLoader(priors_root="outputs/priors")

    # Load priors for a single image
    image_path = "/home/robot/yolo/datasets/PearSurfaceDefects/images/val/cam0_1_557_pear_2.jpg"
    priors = loader.load_priors(image_path, split="val")

    print(f"Likelihood shape: {priors['likelihood'].shape}")
    print(f"Topology mask shape: {priors['topology_mask'].shape}")
    print(f"Metadata: {priors['metadata']}")
