"""
ROI Proposal Module

This module extracts Region of Interest (ROI) proposals from topology masks
generated by Project A. ROIs are used for high-resolution local detection.

Key functionalities:
- Extract connected components from topology_mask
- Filter ROIs by area constraints
- Expand ROIs by a configurable margin
- Convert ROIs to bounding box format
"""

import numpy as np
import cv2
from typing import List, Tuple, Dict
from dataclasses import dataclass


@dataclass
class ROI:
    """
    Region of Interest representation.

    Attributes:
        x1, y1, x2, y2: Bounding box coordinates (xyxy format)
        area: Area in pixels
        centroid: (cx, cy) centroid coordinates
        mask: Binary mask for this ROI (optional)
    """
    x1: int
    y1: int
    x2: int
    y2: int
    area: int
    centroid: Tuple[float, float]
    mask: np.ndarray = None

    def to_xyxy(self) -> Tuple[int, int, int, int]:
        """Return bounding box in xyxy format."""
        return (self.x1, self.y1, self.x2, self.y2)

    def to_xywh(self) -> Tuple[int, int, int, int]:
        """Return bounding box in xywh format."""
        return (self.x1, self.y1, self.x2 - self.x1, self.y2 - self.y1)

    def expand(self, expansion_ratio: float, image_shape: Tuple[int, int]) -> 'ROI':
        """
        Expand the ROI by a given ratio.

        Args:
            expansion_ratio: Expansion ratio (e.g., 0.2 for 20% expansion)
            image_shape: (H, W) to clip coordinates

        Returns:
            New expanded ROI
        """
        w = self.x2 - self.x1
        h = self.y2 - self.y1

        expand_w = int(w * expansion_ratio / 2)
        expand_h = int(h * expansion_ratio / 2)

        new_x1 = max(0, self.x1 - expand_w)
        new_y1 = max(0, self.y1 - expand_h)
        new_x2 = min(image_shape[1], self.x2 + expand_w)
        new_y2 = min(image_shape[0], self.y2 + expand_h)

        return ROI(
            x1=new_x1,
            y1=new_y1,
            x2=new_x2,
            y2=new_y2,
            area=(new_x2 - new_x1) * (new_y2 - new_y1),
            centroid=self.centroid,
            mask=self.mask
        )


class ROIProposer:
    """
    Extracts ROI proposals from topology masks.

    Attributes:
        min_area: Minimum ROI area (pixels)
        max_area: Maximum ROI area (pixels)
        expansion_ratio: ROI expansion ratio
    """

    def __init__(
        self,
        min_area: int = 100,
        max_area: int = 50000,
        expansion_ratio: float = 0.2
    ):
        """
        Initialize ROI proposer.

        Args:
            min_area: Minimum area for valid ROI
            max_area: Maximum area for valid ROI
            expansion_ratio: Expansion ratio (e.g., 0.2 for 20%)
        """
        self.min_area = min_area
        self.max_area = max_area
        self.expansion_ratio = expansion_ratio

    def extract_rois(
        self,
        topology_mask: np.ndarray,
        expand: bool = True
    ) -> List[ROI]:
        """
        Extract ROI proposals from topology mask.

        Args:
            topology_mask: Binary mask [H, W] with values 0 or 1
            expand: Whether to expand ROIs

        Returns:
            List of ROI objects
        """
        # Ensure binary mask
        mask = (topology_mask > 0).astype(np.uint8)

        # Find connected components
        num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(
            mask, connectivity=8
        )

        rois = []

        # Skip label 0 (background)
        for i in range(1, num_labels):
            area = stats[i, cv2.CC_STAT_AREA]

            # Filter by area
            if area < self.min_area or area > self.max_area:
                continue

            # Extract bounding box
            x1 = stats[i, cv2.CC_STAT_LEFT]
            y1 = stats[i, cv2.CC_STAT_TOP]
            w = stats[i, cv2.CC_STAT_WIDTH]
            h = stats[i, cv2.CC_STAT_HEIGHT]
            x2 = x1 + w
            y2 = y1 + h

            # Extract centroid
            cx, cy = centroids[i]

            # Extract component mask
            component_mask = (labels == i).astype(np.uint8)

            roi = ROI(
                x1=x1,
                y1=y1,
                x2=x2,
                y2=y2,
                area=area,
                centroid=(cx, cy),
                mask=component_mask
            )

            # Expand if requested
            if expand:
                roi = roi.expand(self.expansion_ratio, topology_mask.shape)

            rois.append(roi)

        return rois

    def visualize_rois(
        self,
        image: np.ndarray,
        rois: List[ROI],
        color: Tuple[int, int, int] = (255, 0, 0),
        thickness: int = 2
    ) -> np.ndarray:
        """
        Visualize ROIs on an image.

        Args:
            image: Input image [H, W, 3]
            rois: List of ROI objects
            color: Box color (BGR)
            thickness: Line thickness

        Returns:
            Image with ROIs drawn
        """
        vis_image = image.copy()

        for roi in rois:
            cv2.rectangle(
                vis_image,
                (roi.x1, roi.y1),
                (roi.x2, roi.y2),
                color,
                thickness
            )

            # Draw centroid
            cx, cy = int(roi.centroid[0]), int(roi.centroid[1])
            cv2.circle(vis_image, (cx, cy), 3, color, -1)

        return vis_image

    def filter_overlapping_rois(
        self,
        rois: List[ROI],
        iou_threshold: float = 0.5
    ) -> List[ROI]:
        """
        Filter overlapping ROIs using Non-Maximum Suppression.

        Args:
            rois: List of ROI objects
            iou_threshold: IoU threshold for suppression

        Returns:
            Filtered list of ROIs
        """
        if len(rois) == 0:
            return []

        # Convert to numpy array for NMS
        boxes = np.array([roi.to_xyxy() for roi in rois])
        areas = np.array([roi.area for roi in rois])

        # Sort by area (descending)
        order = areas.argsort()[::-1]

        keep = []
        while len(order) > 0:
            i = order[0]
            keep.append(i)

            # Compute IoU with remaining boxes
            xx1 = np.maximum(boxes[i, 0], boxes[order[1:], 0])
            yy1 = np.maximum(boxes[i, 1], boxes[order[1:], 1])
            xx2 = np.minimum(boxes[i, 2], boxes[order[1:], 2])
            yy2 = np.minimum(boxes[i, 3], boxes[order[1:], 3])

            w = np.maximum(0, xx2 - xx1)
            h = np.maximum(0, yy2 - yy1)
            inter = w * h

            iou = inter / (areas[i] + areas[order[1:]] - inter)

            # Keep boxes with IoU below threshold
            inds = np.where(iou <= iou_threshold)[0]
            order = order[inds + 1]

        return [rois[i] for i in keep]


if __name__ == "__main__":
    # Example usage
    proposer = ROIProposer(min_area=100, max_area=50000, expansion_ratio=0.2)

    # Create a dummy topology mask
    mask = np.zeros((1024, 1280), dtype=np.uint8)
    mask[100:200, 150:250] = 1  # Defect region 1
    mask[500:600, 700:800] = 1  # Defect region 2

    # Extract ROIs
    rois = proposer.extract_rois(mask, expand=True)

    print(f"Extracted {len(rois)} ROIs:")
    for i, roi in enumerate(rois):
        print(f"  ROI {i}: {roi.to_xyxy()}, area={roi.area}")
